### ISSUE TITLE
How to configure? "Queue is not functional."

### ISSUE THREAD

**Issue by ryprfpryr** [catalyst/moodle-logstore_standardqueued#25]
We're trying to do some tests with the plugin but we can't figure out how to make it work.

- We have created a queue in SQS with basic configuration and configure the endpoint in the moodle admin settings. We have disabled the moodle standard log plugin.

- We get "Queue is not functional":

![image](https://user-images.githubusercontent.com/68156081/178281532-439a8cb3-0ef4-41a6-b265-8fbd72333faf.png)

![image](https://user-images.githubusercontent.com/68156081/178281551-cfba441b-d76c-430d-912a-20da0ca367ce.png)

What are we missing?
Thanks

**Comment by ryprfpryr** [comment]
@brendanheywood @srdjan-catalyst could you please help me? Thank you very much!

**Comment by brendanheywood** [comment]
hi @ryprfpryr this plugin is a bit of a funny one which is only half published and it is certainly not well documented. I was originally intending that there would be multi adapters for pushing logs into different temporary queues and pulling them back out in batches to insert in to the real logs, but in the end we only implemented a single one which relies on a side car python daemon and the source for that isn't open sourced and most likely won't be as its a little tied up with our infrastructure setup.

So I'm sorry but it's in a weird state. In theory you can get it to write directly to sqs rather than going through our sidecar. This was working at some point but we didn't go with that path because the latency was too high. I can't tell you if that is supposed to still work on not. I know this isn't ideal but if you are interested in chipping in either dev time or funds to iron this out it would be welcome.

**Comment by golenkovm** [comment]
Closing the issue as won't fix.
Sorry about that @ryprfpryr
