### ISSUE TITLE
Live logs report is broken if using this plugin

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-logstore_standardqueued#7]
New records are not coming to the /report/loglive/index.php?logreader=logstore_standardqueued without refreshing the page.

**Comment by srdjan-catalyst** [comment]
That is unfortunate, but it will stay like that unless someone comes up with a great idea.

Ajax polling asks for records with timecreated after last polling time. That is actually wrong as is, with the standard logstore, because records are inserted at the end of the request. That way observer will never get records for other users' requests that started before polling cutoff and finished after it. A small number, I admit, but still.
In case of a queued logging, records are pulled from the queue with a delay of 1 minute (at least, we may push it even more), therefore only a small number of logs can be caught, and even that if polling and cron are aligned favourably.

A suggestion for a a great idea: report_loglive_table_log_ajax reports back "until" to be the current time. should be the max of the 
returned rows timecreated.

**Comment by golenkovm** [comment]
Fetching records by id seems the be the best solution to me. I've created a tracker to fix this in core https://tracker.moodle.org/browse/MDL-73948

**Comment by dmitriim** [comment]
I believe this one can be closed once some info added into a README suggesting about supported versions  or/and something about backporting a patch to get the report working.

**Comment by golenkovm** [comment]
Readme was updated.
